INSERT INTO `sie_sale_contract_t`(`serial_num`, `user_id`, `zh_name`, `org_name`, `customer_manager`, `sale_area`, `pre_sale_po_code`, `pre_sale_owner`, `pre_sale_po_name`, `product_type`, `contract_name`, `customer_code`, `customer_name`, `customer_bill_addr`, `currency`, `contract_entity`, `delivery_org_name`, `billing_type`, `contract_service_begin_date`, `contract_service_end_date`, `bid_num`, `pre_contract_num`, `sale_category`, `is_sh_external`, `frame_agreement_num`, `maintenance_period`, `sh_company`, `impl_dev_amount`, `impl_bu_quote`, `impl_invoice_tax_rate`, `oper_amount`, `oper_bu_quote`, `oper_invoice_tax_rate`, `self_soft_amount`, `self_bu_quote`, `self_invoice_tax_rate`, `out_soft_amount`, `out_purchase_cost`, `out_invoice_tax_rate`, `hard_amount`, `hard_purchase_cost`, `hard_invoice_tax_rate`, `resource_amount`, `resource_purchase_cost`, `resource_invoice_tax_rate`, `is_back_to_back`, `dist_amount`, `predict_dist_total_cost`, `predict_dist_gp`, `contract_total_day`, `standard_person_unit_price`, `predict_hard_soft_gp`, `contract_total_amount`, `risk_person_type`, `risk_person_value`, `risk_sup_description`, `wf_state`, `is_lock`, `tmp_uuid`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES ('RYJXSHT1912240', 12545, '陈荣锋', '40华南销售二部', '陈荣锋', '40华南销售二部', '01GZ19110563', '任泽华', '华为云新增配置项目', '华为云', '云服务销售协议', '3W201903114451', '深圳市骏亚电路科技有限公司', '深圳市福田香蜜湖街道东海社区深南大道7028号时代科技大厦1A0755-82800331', '人民币', '广州赛意信息科技股份有限公司', '30华为业务线', NULL, NULL, NULL, 'TBBJSQ1911270', NULL, '硬件', b'1', NULL, NULL, '其他   ', 0.00, 0.00, NULL, 0.00, 0.00, NULL, 0.00, 0.00, NULL, 0.00, 0.00, NULL, 50000.00, 50000.00, '6%', 0.00, 0.00, NULL, b'0', 50000.00, 50000.00, '0.00%', 0, 0.00, '0.00%', 50000.00, NULL, NULL, NULL, 'completed', b'0', NULL, NULL, '1', '1', '12545', '2019-12-05 09:24:03', '12545', '2019-12-05 09:24:03');

INSERT INTO `sie_sale_contract_abstract_t`(`contract_id`, `serial_num`, `contract_abstract`, `intellectual_property`, `accept_condition`, `breach_clause`, `penalty_condition`, `litigation_land`, `warranty_period`, `description`, `recipient_name`, `recipient_tel`, `recipient_addr`, `wf_state`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8671, 'RYJXSHT1912240', '应用服务器/数据库迁移新够费用\r\n新够数据盘', '乙方保证其提供给甲方的云服务不侵犯第三方知识产权、商业秘密，不存在索赔、留置、抵押、诉讼等权利瑕疵事项，保证服务的来源合法、有效，否则应当承担由此造成的一切法律后果。\r\n\r\n', '甲方需按照乙方要求在规定时间内将邮箱地址及验证码、手机联系方式及验证码、资质牌照等信息提交给乙方，由乙方为甲方在华为云官方网站创建甲方账号并完成实名认证，即视作账号开通，乙方收到全额价款7个工作日内将资源清单华为云资源交付于甲方，即视服务开通,乙方以邮件告知甲方。', '乙方逾期交付所购买产品及服务，每逾期一日，应按订单总价 0.5%向 甲方支付违约金。逾期超过30天，甲方有权解除本订单，乙方除支付本订单总价 的20%作为违约金外，乙方还应赔偿因此给甲方造成的直接及间接损失。\r\n2、若产品及服务存在缺陷或与本订单规定有不符之处，乙方应按照本订单约定履行维护义务，否则，甲方有权自行或聘请第三方消除该缺陷或与本协议规定不符之处，所有费用由乙方承担，并要求乙方支付协议总价款 30%的违约金， 如果上述违约金无法弥补甲方损失，乙方还应赔偿由此给甲方造成的直接及间接损失。\r\n', '乙方对获取的甲方的知识产权、商业秘密进行保密，其范围包括但不限于专有技术、商业计划、版权、公式、图纸、草图、数据、流程、采购价格、会议纪要、经营信息、市场客户资料等，未经甲方许可，不得用于经营或向第三方披露，否则，应承担由此给甲方造成的一切经济损失。', '甲方所在地（深圳）', 12, NULL, NULL, NULL, NULL, 'completed', NULL, '1', '1', '12545', '2019-12-05 09:24:03', '12545', '2019-12-05 09:24:03');

INSERT INTO `sie_sale_contract_opinion_t`(`contract_id`, `serial_num`, `pb_condition_deviation`, `pb_not_description`, `warranty_deviation`, `warranty_not_description`, `intellectual_deviation`, `intellectual_not_description`, `breach_deviation`, `breach_not_description`, `penalty_deviation`, `penalty_not_description`, `litigation_deviation`, `litigation_not_description`, `risk_person_type`, `risk_person_value`, `risk_sup_description`, `account_project_gp`, `account_sup_description`, `stamp_date`, `express_num`, `remark`, `project_location`, `include_or_not_accommodation`, `product_department`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8671, 'RYJXSHT1912240', '是', '预付30%', '否', NULL, '否', NULL, '否', NULL, '否', NULL, '是', '甲方', '无', NULL, NULL, '软硬件采购高于8%或纯资源采购高于10%', NULL, '2019-12-17 00:00:00', 'SF1071476031060', NULL, NULL, NULL, NULL, '1', '1', '12545', '2019-12-05 09:24:03', '12545', '2019-12-05 09:24:03');

INSERT INTO `sie_sale_contract_pb_t`(`contract_id`, `serial_num`, `pb_order`, `sale_category`, `pb_phase`, `pb_condition`, `pb_day`, `pb_ratio`, `predict_date`, `predict_amount`, `remark`, `wf_state`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8671, 'RYJXSHT1912240', 1, '硬件', '硬件款', '订单生效后，甲方于7个工作日内向乙方支付订单总金额的30%', 7.00, '30', '2019-12-25', 15000.00, NULL, 'completed', NULL, '1', '1', '12545', '2019-12-05 09:24:03', '12545', '2019-12-05 09:24:03');

INSERT INTO `sie_sale_contract_pb_t`(`contract_id`, `serial_num`, `pb_order`, `sale_category`, `pb_phase`, `pb_condition`, `pb_day`, `pb_ratio`, `predict_date`, `predict_amount`, `remark`, `wf_state`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8671, 'RYJXSHT1912240', 2, '硬件', '硬件款', '云服务经双方验收合格后1个月内', 30.00, '70', '2020-01-30', 35000.00, NULL, 'completed', NULL, '1', '1', '12545', '2019-12-05 09:24:03', '12545', '2019-12-05 09:24:03');

UPDATE sie_sale_contract_t s1,sie_sale_contract_pb_t s2 set s2.contract_id = s1.id where s1.serial_num = s2.serial_num and s1.serial_num = 'RYJXSHT1912240';
UPDATE sie_sale_contract_t s1,sie_sale_contract_opinion_t s2 set s2.contract_id = s1.id where s1.serial_num = s2.serial_num and s1.serial_num = 'RYJXSHT1912240';
UPDATE sie_sale_contract_t s1,sie_sale_contract_abstract_t s2 set s2.contract_id = s1.id where s1.serial_num = s2.serial_num and s1.serial_num = 'RYJXSHT1912240';