INSERT INTO `sie_sale_contract_t`(`serial_num`, `user_id`, `zh_name`, `org_name`, `customer_manager`, `sale_area`, `pre_sale_po_code`, `pre_sale_owner`, `pre_sale_po_name`, `product_type`, `contract_name`, `customer_code`, `customer_name`, `customer_bill_addr`, `currency`, `contract_entity`, `delivery_org_name`, `billing_type`, `contract_service_begin_date`, `contract_service_end_date`, `bid_num`, `pre_contract_num`, `sale_category`, `is_sh_external`, `frame_agreement_num`, `maintenance_period`, `sh_company`, `impl_dev_amount`, `impl_bu_quote`, `impl_invoice_tax_rate`, `oper_amount`, `oper_bu_quote`, `oper_invoice_tax_rate`, `self_soft_amount`, `self_bu_quote`, `self_invoice_tax_rate`, `out_soft_amount`, `out_purchase_cost`, `out_invoice_tax_rate`, `hard_amount`, `hard_purchase_cost`, `hard_invoice_tax_rate`, `resource_amount`, `resource_purchase_cost`, `resource_invoice_tax_rate`, `is_back_to_back`, `dist_amount`, `predict_dist_total_cost`, `predict_dist_gp`, `contract_total_day`, `standard_person_unit_price`, `predict_hard_soft_gp`, `contract_total_amount`, `risk_person_type`, `risk_person_value`, `risk_sup_description`, `wf_state`, `is_lock`, `tmp_uuid`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES ('RYJXSHT1912261', 10171, '章成楠', '40销售发展一部', '章成楠', '40销售发展一部', '01PS19120062', '朱焕超', '富安莱MES&SCADA系统第一阶段及MINI中控系统硬件采购合同', 'S-MOM-SCADA', '浙江富安莱科技MES&SCADA系统第一阶段及MINI中控系统硬件采购合同', '3W201911045218', '浙江富安莱科技有限公司', '义乌市稠江街道恒通路768号', '人民币元', '广州赛意信息科技股份有限公司', '30行业三部_子行业二部', NULL, NULL, NULL, NULL, NULL, '硬件', b'1', NULL, NULL, '其他   ', 0.00, 0.00, NULL, 0.00, 0.00, NULL, 0.00, 0.00, NULL, 0.00, 0.00, NULL, 720810.00, 607040.00, '13%', 0.00, 0.00, NULL, b'0', 720810.00, 607040.00, '15.78%', 0, 0.00, '15.78%', 720810.00, NULL, NULL, NULL, 'completed', b'0', NULL, NULL, '1', '1', '10171', '2019-12-05 16:00:17', '10171', '2019-12-05 16:00:17');

INSERT INTO `sie_sale_contract_opinion_t`(`contract_id`, `serial_num`, `pb_condition_deviation`, `pb_not_description`, `warranty_deviation`, `warranty_not_description`, `intellectual_deviation`, `intellectual_not_description`, `breach_deviation`, `breach_not_description`, `penalty_deviation`, `penalty_not_description`, `litigation_deviation`, `litigation_not_description`, `risk_person_type`, `risk_person_value`, `risk_sup_description`, `account_project_gp`, `account_sup_description`, `stamp_date`, `express_num`, `remark`, `project_location`, `include_or_not_accommodation`, `product_department`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8723, 'RYJXSHT1912261', '是', '硬件分三次回款', '否', NULL, '否', NULL, '否', NULL, '否', NULL, '否', NULL, '无', NULL, NULL, '软硬件采购高于8%或纯资源采购高于10%', NULL, '2019-12-16 00:00:00', NULL, NULL, NULL, NULL, NULL, '1', '1', '10171', '2019-12-05 16:00:17', '10171', '2019-12-05 16:00:17');

INSERT INTO `sie_sale_contract_abstract_t`(`contract_id`, `serial_num`, `contract_abstract`, `intellectual_property`, `accept_condition`, `breach_clause`, `penalty_condition`, `litigation_land`, `warranty_period`, `description`, `recipient_name`, `recipient_tel`, `recipient_addr`, `wf_state`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8723, 'RYJXSHT1912261', '事由富安莱科技MES&SCADA项目所需硬件采购合同', '无', '3.1乙方承诺在收到首期款后  30 个工作日内将产品运至甲方指定的交付地点，甲方或其指定的收货方应接收产品。如乙方将产品运至交货地址，但甲方或其指定的收货方无正当理由拒收产品，则由甲方承担责任，甲方应赔偿乙方因此所受的一切损失。\r\n物流信息显示甲方或其指定的收货方（包括甲方或其指定的收货方的工作人员）已经签收货物，或者已在物流配送单据上签字，即视为产品交付的完成。 \r\n3.2甲、乙双方应在乙方交付完成当日对产品的【数量、品牌、规格、型号、包装】进行验收，如果与本协议约定不符，则甲方应当于交付完成【3】日内向乙方说明，否则视为产品的【数量、品牌、规格、型号、包装】符合本合同的约定。\r\n3.3甲、乙双方应在乙方对产品进行安装调试合格后的5日内验收,如果甲方或其指定收货方发现产品不符本协议的约定，则甲方应当于乙方交付完成后的【5】日内提出书面异议，否则视为产品已经验收。\r\n', '6.1	若甲方未按约如期付款，乙方有权向甲方主张违约金，违约金按逾期付款金额日千分之一计算。\r\n6.2	若乙方未按约如期交货，甲方有权向乙方主张违约金，违约金按逾期交货金额日千分之一计算。\r\n6.3	一方因违约行为造成另一方损失的，应当赔偿另一方因此而遭受的损失，包括但不限于诉讼费、律师费等其他为了主张权利而支付的全部费用。\r\n6.4	因原厂家的产品质量问题或者因原厂家产品侵犯第三方权利而对甲方造成的损害，乙方不承担任何责任，但乙方应配合甲方向原厂家主张损害赔偿。\r\n', '无', '原告', 12, NULL, NULL, NULL, NULL, 'completed', NULL, '1', '1', '10171', '2019-12-05 16:00:17', '10171', '2019-12-05 16:00:17');

INSERT INTO `sie_sale_contract_pb_t`(`contract_id`, `serial_num`, `pb_order`, `sale_category`, `pb_phase`, `pb_condition`, `pb_day`, `pb_ratio`, `predict_date`, `predict_amount`, `remark`, `wf_state`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8723, 'RYJXSHT1912261', 2, '硬件', '硬件款', '硬件产品到厂验收后，收到发票之日起', 15.00, '60', '2020-01-31', 432486.00, NULL, 'completed', NULL, '1', '1', '10171', '2019-12-05 16:00:17', '10171', '2019-12-05 16:00:17');
INSERT INTO `sie_sale_contract_pb_t`(`contract_id`, `serial_num`, `pb_order`, `sale_category`, `pb_phase`, `pb_condition`, `pb_day`, `pb_ratio`, `predict_date`, `predict_amount`, `remark`, `wf_state`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8723, 'RYJXSHT1912261', 1, '硬件', '硬件款', '合同签订，且收到发票之日起', 15.00, '30', '2019-12-20', 216243.00, NULL, 'completed', NULL, '1', '1', '10171', '2019-12-05 16:00:17', '10171', '2019-12-05 16:00:17');
INSERT INTO `sie_sale_contract_pb_t`(`contract_id`, `serial_num`, `pb_order`, `sale_category`, `pb_phase`, `pb_condition`, `pb_day`, `pb_ratio`, `predict_date`, `predict_amount`, `remark`, `wf_state`, `extra`, `data_state`, `old_data`, `created_by`, `created_date`, `last_modified_by`, `last_modified_date`) VALUES (8723, 'RYJXSHT1912261', 3, '硬件', '硬件款', '硬件安装上电调试测试合格后，且收到发票之日起', 15.00, '10', '2020-03-31', 72081.00, NULL, 'completed', NULL, '1', '1', '10171', '2019-12-05 16:00:17', '10171', '2019-12-05 16:00:17');

UPDATE sie_sale_contract_t s1,sie_sale_contract_pb_t s2 set s2.contract_id = s1.id where s1.serial_num = s2.serial_num and s1.serial_num = 'RYJXSHT1912261';
UPDATE sie_sale_contract_t s1,sie_sale_contract_opinion_t s2 set s2.contract_id = s1.id where s1.serial_num = s2.serial_num and s1.serial_num = 'RYJXSHT1912261';
UPDATE sie_sale_contract_t s1,sie_sale_contract_abstract_t s2 set s2.contract_id = s1.id where s1.serial_num = s2.serial_num and s1.serial_num = 'RYJXSHT1912261';